apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: my-app
  namespace: wordpress
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"

